


###
POST http://127.0.0.1:3000/MeasureCate
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "CompanyCode": "C280"
      }
    }
  }
}


###
POST https://zquzsuba13.cfapps.ap21.hana.ondemand.com/MeasureCate
Content-Type: application/json

{
    "requestBody":
    {"case": 
    {"extensions": 
    { "CompanyCode": "C280" 
    } 
}
    }
}