###
POST http://127.0.0.1:3000/summary1
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "categoryLevel1": {
        "name": "Domestic"
      },
      "extensions": {
        "Postingdate": "2025-11-18"
      },
      "categoryLevel2": {
        "name": "Conference fees"
      },
      "caseType": "ZBTF"
    }
  }
}

###
POST http://127.0.0.1:3000/summary1
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "categoryLevel1": {
        "name": "国内"
      },
      "extensions": {
        "Postingdate": "2025-11-18"
      },
      "categoryLevel2": {
        "name": ""
      },
      "caseType": "ZBTF"
    }
  }
}

###
POST http://127.0.0.1:3000/summary1
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "categoryLevel1": {
        "name": "国内"
      },
      "extensions": {
        "Postingdate": "2017/4/1"
      },
      "categoryLevel2": {
        "name": "会議費"
      },
      "caseType": "ZBTF"
    }
  }
}

###
POST http://127.0.0.1:3000/summary2
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "桃プロ"
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2023/4/8"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/summary2
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "源泉付支払"
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2023/4/8"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/summary3
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "桃プロ",
          "F_summary2": "社員のみ(JTBCへの出向者含む)での飲食代"
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/summary3
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "税理士報酬（取引相手が個人事業主等の源泉対象者）",
          "F_summary2": ""
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/summary4
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "各種協会、団体等の会費",
          "F_summary2": "国内に所在する各種協会、団体",
          "F_summary3": "上記以外"
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/summary4
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "特定公益増進法人への寄付",
          "F_summary2": "物品による寄付",
          "F_summary3": ""
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/summary5
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "電算費経費",
          "F_summary2": "ＯＡ関連物品の購入",
          "F_summary3": "使用期間が1年以上のもの",
          "F_summary4": "税抜単価100,000円未満の物品購入"
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/summary5
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "社外関係者(JTBC勤務者以外)が同席した飲食代",
          "F_summary2": "国内業者との取引：税抜単価10,000円超",
          "F_summary3": "軽減税率 税率8％",
          "F_summary4": ""
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/summary6
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "企画担当",
          "F_summary2": "消耗品費(事務用品･日用品･書籍･新聞購読料･ｶﾞｿﾘﾝ等)",
          "F_summary3": "その他消耗品等の購入",
          "F_summary4": "1単体税抜単価100,000円未満",
          "F_summary5": "海外購入分(課税対象外･不課税･免税)"
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/summary6
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "社員のみ(JTBCへの出向者含む)での飲食代",
          "F_summary2": "打合せ・会議に伴う喫茶・飲食代",
          "F_summary3": "会議場所等、同一施設内での飲食",
          "F_summary4": "海外出張時等の取引：単価3,000円以下",
          "F_summary5": ""
        }
      ]
    },
    "case": {
      "extensions": {
        "Postingdate": "2025/10/1"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/AccountCode
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "企画担当",
          "F_summary2": "消耗品費(事務用品･日用品･書籍･新聞購読料･ｶﾞｿﾘﾝ等)",
          "F_summary3": "その他消耗品等の購入",
          "F_summary4": "1単体税抜単価100,000円未満",
          "F_summary5": "国内購入分･消費税が含まれている(課税)",
          "F_summary6": "TestB"
        }
      ]
    }
  }
}


###
POST http://127.0.0.1:3000/AccountCode
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary5": "海外購入分(課税対象外･不課税･免税)",
          "F_summary6": "TestA",
          "F_summary1": "企画担当",
          "F_summary2": "消耗品費(事務用品･日用品･書籍･新聞購読料･ｶﾞｿﾘﾝ等)",
          "F_summary3": "その他消耗品等の購入",
          "F_summary4": "1単体税抜単価100,000円未満"
        }
      ]
    }
  }
}

###
POST http://127.0.0.1:3000/EnterExpenses
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "社外関係者(JTBC勤務者以外)が同席した飲食代",
          "F_summary2": "国内業者との取引：税抜単価10,000円超",
          "F_summary3": "税率10％",
          "F_summary4": "",
          "F_summary5": "",
          "F_summary6": ""
        }
      ]
    }
  }
}



###
POST http://127.0.0.1:3000/Research
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary5": "海外購入分(課税対象外･不課税･免税)",
          "F_summary6": "TestA",
          "F_summary1": "企画担当",
          "F_summary2": "消耗品費(事務用品･日用品･書籍･新聞購読料･ｶﾞｿﾘﾝ等)",
          "F_summary3": "その他消耗品等の購入",
          "F_summary4": "1単体税抜単価100,000円未満"
        }
      ]
    }
  }
}


###
POST http://127.0.0.1:3000/DocCurrAmt
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_Doc_curr_amt": "99990",
          "F_Enter_expenses": "02",
          "F_Account_Code": "4569000000"
        }
      ]
    }
  }
}


###
POST http://127.0.0.1:3000/DocCurrAmt
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_Doc_curr_amt": "99990",
          "F_Enter_expenses": "02",
          "F_Account_Code": "4569000000"
        }
      ],
      "F_Resolution": "11"
    }
  }
}


###
POST https://zquzsuba06.cfapps.ap21.hana.ondemand.com/AccountCode
Content-Type: application/json

{
  "requestBody": {
    "Form": {
      "F_meisai": [
        {
          "F_summary1": "企画担当",
          "F_summary2": "消耗品費(事務用品･日用品･書籍･新聞購読料･ｶﾞｿﾘﾝ等)",
          "F_summary3": "その他消耗品等の購入",
          "F_summary4": "1単体税抜単価100,000円未満",
          "F_summary5": "海外購入分(課税対象外･不課税･免税)",
          "F_summary6": "TestA"
        }
      ]
    }
  }
}