
###
POST http://127.0.0.1:3000/PostingDate
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "Postingdate": "2025/11/06"
      }
    }
  }
}



###
POST http://127.0.0.1:3000/PaymentMethod
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "paymentmethod": "11"
      }
    }
  }
}


###
POST http://127.0.0.1:3000/PaymentDate
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "PaymentDate": "2025/11/02"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/Currency
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "currency": "JPY"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/Rate
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "Rate": "3.14"
      }
    }
  }
}

###
POST http://127.0.0.1:3000/TotalAmount
Content-Type: application/json

{
  "requestBody": {
    "case": {
      "extensions": {
        "Total_amount": 123        
      }
    }
  }
}